name: Fix Code Style

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install
        run: ./bin/install
      - name: Pint
        run: ./vendor/bin/sail composer pint
