name: Testing

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Pages
              if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
              uses: actions/configure-pages@v4
            - name: Cache Composer
              id: cache-composer
              uses: actions/cache@v3
              with:
                path: vendor
                key: ${{ hashFiles('composer.lock') }}
            - name: Cache NPM
              id: cache-npm
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ hashFiles('package-lock.json') }}
            - name: Install
              run: ./_docker/bin/util/install
            - name: Start
              run: ./_docker/bin/util/start
            - name: Deptrac
              run: ./_docker/bin/app/deptrac
              if: always()
            - name: ECS
              run: ./_docker/bin/app/ecs
              if: always()
            - name: Stan
              run: ./_docker/bin/app/composer stan
              if: always()
            - name: Coverage
              id: coverage
              run: ./_docker/bin/app/phpunit-with-coverage
              if: always()
            - uses: actions/cache/save@v3
              id: cache
              if: steps.coverage.outputs.exit_code == 0
              with:
                key: code-coverage-${{ github.sha }}
                path: ./code-coverage

    static_upload:
        needs: testing
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
        - uses: actions/cache/restore@v3
          id: cache-download
          with:
            path: ./code-coverage
            key: code-coverage-${{ github.sha }}
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: ./code-coverage
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
